name = "MeshfreeTrixi"
uuid = "fd449e90-7bb5-416e-be12-8a17b6c6ab2b"
authors = ["jarias9 <68081892+jarias9@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
